FROM node:alpine

MAINTAINER onlinegears

RUN apk add --no-cache git python

# front end
RUN npm install -g react-tools
RUN npm install -g @angular/cli
# back end
RUN npm install -g express
RUN npm install -g express-generator
# web3js
RUN npm install -g web3
